packages:
  - 'packages/ui'
  - 'packages/demo-nuxt'
  - 'packages/demo-vue'
  - 'packages/create-ui'

overrides:
  vite: 8.0.14
  vite-plugin-inspect: 12.0.0-beta.2

peerDependencyRules:
  allowedVersions:
    '@nuxt/kit': '4'
    eslint: '8'

allowBuilds:
  '@parcel/watcher': set this to true or false
  esbuild: true
  simple-git-hooks: true
  vue-demi: true
publishBranch: main
dude: true
shamefullyHoist: true
shellEmulator: true
