export { default as XTable } from './Table.vue'
export { default as XTableBody } from './TableBody'
export { default as XTableCell } from './TableCell.vue'
export { default as XTableHead } from './TableHead.vue'
export { default as XTableHeader } from './TableHeader.vue'
export { default as XTableRow } from './TableRow.vue'

export type { TableProps, TableHeader, TableTheme } from './Table.vue'
export type { TableHeadProps, TableHeadTheme } from './TableHead.vue'
export type { TableRowProps, TableRowTheme } from './TableRow.vue'
export type { TableHeaderProps, TableHeaderAlign, TableHeaderSort, TableHeaderTheme } from './TableHeader.vue'
export type { TableCellProps, TableCellTextAlign, TableCellVerticalAlign, TableCellTheme } from './TableCell.vue'
