declare module 'vue' {
  export interface GlobalComponents {
    XAlert: typeof import('@indielayer/ui')['XAlert']
    XAvatar: typeof import('@indielayer/ui')['XAvatar']
    XBadge: typeof import('@indielayer/ui')['XBadge']
    XBreadcrumbs: typeof import('@indielayer/ui')['XBreadcrumbs']
    XButton: typeof import('@indielayer/ui')['XButton']
    XButtonGroup: typeof import('@indielayer/ui')['XButtonGroup']
    XCard: typeof import('@indielayer/ui')['XCard']
    XCheckbox: typeof import('@indielayer/ui')['XCheckbox']
    XCollapse: typeof import('@indielayer/ui')['XCollapse']
    XContainer: typeof import('@indielayer/ui')['XContainer']
    XDivider: typeof import('@indielayer/ui')['XDivider']
    XDrawer: typeof import('@indielayer/ui')['XDrawer']
    XForm: typeof import('@indielayer/ui')['XForm']
    XIcon: typeof import('@indielayer/ui')['XIcon']
    XImage: typeof import('@indielayer/ui')['XImage']
    XInput: typeof import('@indielayer/ui')['XInput']
    XLink: typeof import('@indielayer/ui')['XLink']
    XMenu: typeof import('@indielayer/ui')['XMenu']
    XMenuItem: typeof import('@indielayer/ui')['XMenuItem']
    XModal: typeof import('@indielayer/ui')['XModal']
    XNotifications: typeof import('@indielayer/ui')['XNotifications']
    XPagination: typeof import('@indielayer/ui')['XPagination']
    XPaginationItem: typeof import('@indielayer/ui')['XPaginationItem']
    XPopover: typeof import('@indielayer/ui')['XPopover']
    XPopoverContainer: typeof import('@indielayer/ui')['XPopoverContainer']
    XProgress: typeof import('@indielayer/ui')['XProgress']
    XRadio: typeof import('@indielayer/ui')['XRadio']
    XScroll: typeof import('@indielayer/ui')['XScroll']
    XSelect: typeof import('@indielayer/ui')['XSelect']
    XSkeleton: typeof import('@indielayer/ui')['XSkeleton']
    XSlider: typeof import('@indielayer/ui')['XSlider']
    XSpacer: typeof import('@indielayer/ui')['XSpacer']
    XSpinner: typeof import('@indielayer/ui')['XSpinner']
    XTable: typeof import('@indielayer/ui')['XTable']
    XTableBody: typeof import('@indielayer/ui')['XTableBody']
    XTableCell: typeof import('@indielayer/ui')['XTableCell']
    XTableHead: typeof import('@indielayer/ui')['XTableHead']
    XTableHeader: typeof import('@indielayer/ui')['XTableHeader']
    XTableRow: typeof import('@indielayer/ui')['XTableRow']
    XTab: typeof import('@indielayer/ui')['XTab']
    XTabGroup: typeof import('@indielayer/ui')['XTabGroup']
    XTag: typeof import('@indielayer/ui')['XTag']
    XTextarea: typeof import('@indielayer/ui')['XTextarea']
    XToggle: typeof import('@indielayer/ui')['XToggle']
    XTooltip: typeof import('@indielayer/ui')['XTooltip']
    [key: string]: any
  }
}

export {}
