name: Create Github release
run-name: Creating GH release - ${{ github.ref_name }}

on:
  push:
    tags:
      - "**"

jobs:
  check:
    runs-on: ubuntu-20.04
    steps:
      - name: Validate release target
        if: ${{ github.ref_name != github.event.repository.default_branch }}
        run: exit 1

  release:
    needs:
      - check
    runs-on: ubuntu-20.04
    steps:
      - name: "Create release"
        uses: "actions/github-script@v5"
        with:
          github-token: ${{ secrets.P_GITHUB_TOKEN }}
          script: |
            const pkg = '${{ github.ref_name}}'.match(/@indielayer\/(.*)@/)[1];
            github.rest.repos.createRelease({
              draft: false,
              generate_release_notes: false,
              name: '${{ github.ref_name}}',
              owner: context.repo.owner,
              prerelease: false,
              repo: context.repo.repo,
              body: `Please refer to [CHANGELOG.md](https://github.com/indielayer/ui/blob/master/packages/${pkg}/CHANGELOG.md) for details.`,
              tag_name: '${{ github.ref_name}}',
            });
