name: Pull Request Check
run-name: Pull Request Check - ${{ github.ref_name }}

on:
  pull_request:
    branches: ["main", "master"]

concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  release:
    name: Pull Request Check - ${{ github.ref_name }}
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@8912a9102ac27614460f54aedde9e1e7f9aec20d # v6.0.5

      - name: Use Node.js 24
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --ignore-scripts

      - name: Linting
        run: |
          pnpm run lint:ui
          pnpm run lint:style

      - name: Unit tests
        run: pnpm run test

      - name: Build documentation
        run: pnpm run build:docs
