name: Release production
run-name: Release production - ${{ github.ref_name }}

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.P_GITHUB_TOKEN }}

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: "pnpm"
          cache-dependency-path: "pnpm-lock.yaml"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --ignore-scripts

      - name: Create Release Pull Request & Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm run release
          commit: "chore: release packages"
          title: "chore: release packages production"
        env:
          GITHUB_TOKEN: ${{ secrets.P_GITHUB_TOKEN }}
