name: Release production
run-name: Release production - ${{ github.ref_name }}

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          token: ${{ secrets.P_GITHUB_TOKEN }}

      - name: Install pnpm
        uses: pnpm/action-setup@8912a9102ac27614460f54aedde9e1e7f9aec20d # v6.0.5
        with:
          version: 11

      - name: Use Node.js 24
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: "pnpm"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: pnpm install --ignore-scripts

      - name: Create Release Pull Request & Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm run release
          commit: "chore: release packages"
          title: "chore: release packages production"
        env:
          GITHUB_TOKEN: ${{ secrets.P_GITHUB_TOKEN }}
