name: Update docs

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          token: ${{ secrets.P_GITHUB_TOKEN }}

      - name: Install pnpm
        uses: pnpm/action-setup@8912a9102ac27614460f54aedde9e1e7f9aec20d # v6.0.5

      - name: Use Node.js 24
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --ignore-scripts

      - name: Build documentation
        run: |
          pnpm run build:docs
          cp ./packages/ui/dist/index.html ./packages/ui/dist/404.html

      - name: Update pages
        working-directory: ./packages/ui/dist
        run: |
          git config --global init.defaultBranch master
          git init
          git config user.name 'indielayer-ci'
          git config user.email 'bot+ci@indielayer.com'
          git add .
          git commit -m "chore: deploy documentation: ${{github.sha}}"
          git push -f https://${{ secrets.P_GITHUB_TOKEN }}@github.com/indielayer/ui master:gh-pages
